feat: Add traffic streams
MeltanoLabs/tap-github pull request #193
Opened 2023-04-19 15:30 UTC by sicarul

This PR adds the Traffic streams to collect how much traffic did we have on each Repository.

It'll only collect data for the repositories the token has write access to, and will log an info message for those that it couldn't collect.

2023-04-19 17:31 UTC, sicarul commented on tap_github/repository_streams.py
> +                    (f"We do not have permissions for this repository: e \t")
Applied!

2023-04-20 21:03 UTC, sicarul commented
It seems the test failed:

```

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tap_github/tests/test_tap.py::test_get_a_repository_in_repo_list_mode[False] - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
FAILED tap_github/tests/test_tap.py::test_get_a_repository_in_repo_list_mode[True] - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
FAILED tap_github/tests/test_tap.py::test_last_state_message_is_valid - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
============= 3 failed, 7 passed, 714 warnings in 84.81s (0:01:24) =============
Error: Process completed with exit code 1.
```

I think it's because of a permissions issue on the user running the test.

2023-04-21 23:33 UTC, edgarrmondragon commented
> It seems the test failed:
> 
> ```
> 
> -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
> =========================== short test summary info ============================
> FAILED tap_github/tests/test_tap.py::test_get_a_repository_in_repo_list_mode[False] - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
> FAILED tap_github/tests/test_tap.py::test_get_a_repository_in_repo_list_mode[True] - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
> FAILED tap_github/tests/test_tap.py::test_last_state_message_is_valid - singer_sdk.exceptions.FatalAPIError: 403 Client Error: b'{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/metrics/traffic#get-repository-clones"}' (Reason: Forbidden) for path: /repos/MeltanoLabs/tap-github/traffic/clones
> ============= 3 failed, 7 passed, 714 warnings in 84.81s (0:01:24) =============
> Error: Process completed with exit code 1.
> ```
> 
> I think it's because of a permissions issue on the user running the test.

@sicarul Yeah, can you add note to the readme documenting which permissions are required to pull the traffic streams?

2023-04-23 03:00 UTC, sicarul commented
Added @edgarrmondragon !

2023-04-26 18:44 UTC, sicarul commented
@edgarrmondragon do we need anything else to move this forward?

2023-04-27 22:35 UTC, edgarrmondragon commented
> @edgarrmondragon do we need anything else to move this forward?

@sicarul Tests are still failing so I worry that this may cause similar failures to users of the tap if their tokens don't support pulling from the traffic endpoints.

Wdyt about adding a tap setting (e.g. `sync_traffic_streams`) that by default makes the tap omit these streams?

cc @kgpayne if you have other ideas

2023-04-27 22:38 UTC, sicarul commented
> > @edgarrmondragon do we need anything else to move this forward?
> 
> @sicarul Tests are still failing so I worry that this may cause similar failures to users of the tap if their tokens don't support pulling from the traffic endpoints.
> 
> Wdyt about adding a tap setting (e.g. `sync_traffic_streams`) that by default makes the tap omit these streams?
> 
> cc @kgpayne if you have other ideas

Maybe i could also handle this error instead?
“ Resource not accessible by integration”

However, i do not believe any user would try to run this entire tap without selecting streams, some are monstruous.

2023-04-28 16:23 UTC, edgarrmondragon commented
> However, i do not believe any user would try to run this entire tap without selecting streams, some are monstruous.

@sicarul You're right, but the SDK tries to be helpful to folks just getting started with singer.io and so all streams are selected by default if no catalog is passed.

However, we could change that in your streams. I'll propose some changes.

(I also started a discussion in the SDK: https://github.com/meltano/sdk/discussions/1652)

2023-04-28 16:35 UTC, edgarrmondragon requested changes

2023-04-28 16:35 UTC, edgarrmondragon commented on tap_github/repository_streams.py
> +            raise
```suggestion
        if response.status_code == 403:
            contents = response.json()
            if contents["message"] == "Resource not accessible by integration":
                self.logger.info("Permissions missing to sync stream '%s'", self.name)
                return
        super().validate_response(response)
```

2023-04-28 16:35 UTC, edgarrmondragon commented on tap_github/repository_streams.py
> +
```suggestion
    """Base class for Traffic Streams"""

    @property
    def metadata(self):
        """Override default selection metadata for this stream.
        
        TODO: Remove this in favor of the recommended approach when the SDK has one.
        """
        result = super().metadata
        if self._tap_input_catalog is None:
            result.root.selected = False
        return result

```

2023-05-03 14:55 UTC, sicarul commented on tap_github/repository_streams.py
> +        """
Accepted!

2023-05-03 15:08 UTC, edgarrmondragon requested changes

2023-05-03 15:08 UTC, edgarrmondragon commented on tap_github/repository_streams.py
> +        """
```suggestion
        """Override default selection metadata for this stream.

        TODO: Remove this in favor of the recommended approach when the SDK has one.
        """
```

2023-05-03 18:54 UTC, edgarrmondragon commented on README.md
> +* For the traffic_* streams, [you will need write access to the repository](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28)
```suggestion
* For the `traffic_*` streams, [you will need write access to the repository](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28). You can enable extraction for these streams by [selecting them in the catalog](https://hub.meltano.com/singer/spec/#metadata).
```

2023-05-03 18:55 UTC, edgarrmondragon commented
@sicarul this LGTM! Just a minor comment on the readme and this is good to merge for me 🙂

2023-05-05 14:00 UTC, laurentS approved these changes

2023-05-05 15:56 UTC, edgarrmondragon commented
Thanks @sicarul!

2023-05-05 15:56 UTC, merged