Initialize UserStream
MeltanoLabs/tap-github pull request #30
Opened 2021-10-08 19:02 UTC by ericboucher

I am trying to add new streams with `users` as the parent instead of `repositories`, but is proving to be a lot more complex than I anticipated.

So I am opening this draft PR to discuss the best strategy.

I started by splitting the streams into `repository_streams` and `user_streams`. But then I am not sure how to best differentiate them. Should it be a completely different tap?

The tests are definitely heavily skewed towards `repositories` at the moment. Would love your input @aaronsteers and @laurentS

2021-11-11 16:40 UTC, edgarrmondragon commented on tap_github/tap.py
>      def discover_streams(self) -> List[Stream]:
@ericboucher it's merged

2021-11-14 15:04 UTC, ericboucher commented
@aaronsteers @edgarrmondragon ready for final review :)

2021-11-16 01:51 UTC, edgarrmondragon requested changes

2021-11-16 01:51 UTC, edgarrmondragon commented on tap_github/tap.py
> +            return [UserStream(tap=self)]
Should these operation "modes" be documented in the project's readme?

2021-11-25 02:31 UTC, edgarrmondragon approved these changes
lgtm!

2021-11-25 10:21 UTC, ericboucher commented
@edgarrmondragon ready to go :)

2021-11-26 21:06 UTC, merged